import { Strategy } from './strategies';

class ScannerBridgeClass {
  private isListening = false;

  public pushTick(assetName: string, price: number, strategies: Strategy[]) {
    console.log(`[AI Scanner] Tick received -> ${assetName}: ${price}`);
  }

  public initLiveTickStream(onTickCallback?: (symbol: string, price: number) => void) {
    if (this.isListening) return;

    const globalWin = window as any;
    const api = globalWin.LiveApi || globalWin.BinarySocket || globalWin.api;
    const rawWs = api?.ws || globalWin.ws || globalWin.appCtx?.websocketInstance;

    if (api && typeof api.send === 'function' && (!rawWs || rawWs.readyState === 1)) {
      const symbols = ['R_10', 'R_25', 'R_50', 'R_75', 'R_100', '1HZ50', '1HZ100'];

      symbols.forEach((symbol) => {
        try {
          api.send({ ticks: symbol, subscribe: 1 }).then((response: any) => {
            if (response && response.tick) {
              this.pushTick(response.tick.symbol, response.tick.quote, []);
              if (onTickCallback) {
                onTickCallback(response.tick.symbol, response.tick.quote);
              }
            }
          }).catch((err: any) => {
            console.warn('[AI Scanner] Subscribing deferred for symbol:', symbol, err);
          });
        } catch (e) {
          console.error('[AI Scanner] Error calling api.send:', e);
        }
      });

      this.isListening = true;
      console.log('[AI Scanner] Successfully subscribed via official Deriv API client.');
    } else {
      setTimeout(() => this.initLiveTickStream(onTickCallback), 3000);
    }
  }

  private normalizeSymbol(marketOrVol: string): string {
    if (!marketOrVol) return '1HZ50';
    const text = marketOrVol.toLowerCase();
    
    if (text.includes('10s') || text.includes('1hz10')) return '1HZ10';
    if (text.includes('25s') || text.includes('1hz25')) return '1HZ25';
    if (text.includes('50s') || text.includes('1hz50')) return '1HZ50';
    if (text.includes('75s') || text.includes('1hz75')) return '1HZ75';
    if (text.includes('100s') || text.includes('1hz100')) return '1HZ100';

    if (text.includes('10')) return 'R_10';
    if (text.includes('25')) return 'R_25';
    if (text.includes('50')) return 'R_50';
    if (text.includes('75')) return 'R_75';
    if (text.includes('100')) return 'R_100';

    return '1HZ50';
  }

  public loadStrategyToWorkspace(strategy: any, options: { stake: number; stopLoss: number; takeProfit?: number; duration?: number; symbol?: string; contractType?: string; [key: string]: any }) {
    console.log(`[AI Scanner] Injecting parameters into workspace:`, strategy, options);

    const globalWin = window as any;
    const targetSymbol = options.symbol || this.normalizeSymbol(strategy.market || strategy.volatility);
    
    // Explicitly derive clean uppercase direction mapping for purchase conditions
    const rawDirection = String(options.contractType || strategy.direction || strategy.tradeType || 'UP').toUpperCase();
    const isFall = rawDirection.includes('DOWN') || rawDirection.includes('PUT') || rawDirection.includes('FALL');
    const targetContract = isFall ? 'PUT' : 'CALL';
    const blocklyTradeType = isFall ? 'Fall' : 'Rise';

    globalWin.tredapendingParams = { ...options, symbol: targetSymbol, contractType: targetContract, strategy };

    // 1. Trigger the Quick Strategy store to programmatically generate blocks on the workspace canvas
    const rootStore = globalWin.derivBotAppStore;
    if (rootStore?.quick_strategy) {
      const quickStrategy = rootStore.quick_strategy;
      try {
        if (typeof quickStrategy.setValue === 'function') {
          quickStrategy.setValue('symbol', targetSymbol);
          quickStrategy.setValue('duration', options.duration || 5);
          quickStrategy.setValue('amount', options.stake);
          quickStrategy.setValue('contract_type', blocklyTradeType);
          quickStrategy.setValue('type', isFall ? 'fall' : 'rise');
        }
        
        const mockFormData = {
          symbol: targetSymbol, 
          durationtype: 't', 
          duration: options.duration || 5,
          stake: options.stake,
          amount: options.stake,
          tradetype: 'rise_fall',
          contract_type: blocklyTradeType,
          type: isFall ? 'fall' : 'rise'
        };

        const submitAction = quickStrategy.onSubmit || quickStrategy.createStrategy;
        if (typeof submitAction === 'function') {
          Promise.resolve(submitAction.call(quickStrategy, mockFormData)).catch(err => {
            console.warn("[ScannerBridge] Store submission caught warning:", err);
          });
        }
      } catch (error) {
        console.warn("[ScannerBridge] Quick strategy store method failed:", error);
      }
    }

    // 2. Safe Canvas Sweep after blocks are generated by the store
    setTimeout(() => {
      let workspace = globalWin.Blockly?.derivWorkspace || globalWin.Blockly?.getMainWorkspace?.();
      if (!workspace) return;

      try {
        const allBlocks = workspace.getAllBlocks(false);
        let blockInjectionCounter = 0;

        allBlocks.forEach((block: any) => {
          // Configure Trade Definition (Market, Submarket, Symbol, and Trade Type)
          if (block.type === 'trade_definition') {
            const marketField = block.getField('MARKET_LIST');
            if (marketField) {
              marketField.setValue('synthetic_index');
              blockInjectionCounter++;
            }

            const submarketField = block.getField('SUBMARKET_LIST');
            if (submarketField) {
              submarketField.setValue('continuous_indices');
              blockInjectionCounter++;
            }

            const symbolField = block.getField('SYMBOL_LIST');
            if (symbolField) {
              if (typeof symbolField.setValue === 'function') {
                symbolField.setValue(targetSymbol);
              }
              if (typeof symbolField.forceRerender === 'function') {
                symbolField.forceRerender();
              } else if (typeof symbolField.beginEdit === 'function' && typeof symbolField.endEdit === 'function') {
                symbolField.beginEdit();
                symbolField.endEdit();
              }
              blockInjectionCounter++;
            }
            
            const tradeTypeField = block.getField('TRADE_TYPE_LIST');
            if (tradeTypeField) {
              tradeTypeField.setValue('callput'); 
              blockInjectionCounter++;
            }
          }

          // Configure Purchase / Contract Type block (CALL / PUT) directly and reliably
          if (block.type === 'purchase' || block.type.includes('purchase') || block.type === 'trade_definition_purchase') {
            const purchaseField = block.getField('PURCHASE_LIST') || block.getField('CONTRACT_TYPE') || block.getField('CB_List');
            if (purchaseField && typeof purchaseField.setValue === 'function') {
              purchaseField.setValue(targetContract);
              blockInjectionCounter++;
            }
          }

          // Configure Stake, Amount, and Duration options
          if (block.type === 'trade_definition_tradeoptions' || block.type.includes('trade') || block.type.includes('amount')) {
            ['AMOUNT', 'VALUE', 'NUM', 'STAKE', 'DURATION'].forEach(fieldName => {
              const field = block.getField(fieldName);
              if (field) {
                if (fieldName === 'DURATION') {
                  const safeDuration = options.duration !== undefined ? Math.min(Math.max(options.duration, 1), 10) : 5;
                  field.setValue(String(safeDuration));
                  blockInjectionCounter++;
                } else if (fieldName !== 'DURATION' && options.stake !== undefined) {
                  field.setValue(String(options.stake));
                  blockInjectionCounter++;
                }
              }
            });

            block.inputList?.forEach((input: any) => {
              const targetBlock = input.connection?.targetBlock();
              if (targetBlock) {
                ['NUM', 'AMOUNT', 'VALUE'].forEach(numFieldName => {
                  const numField = targetBlock.getField(numFieldName);
                  if (numField) {
                    if (input.name === 'AMOUNT' && options.stake !== undefined) {
                      numField.setValue(String(options.stake));
                      blockInjectionCounter++;
                    } else if (input.name === 'DURATION') {
                      const safeDuration = options.duration !== undefined ? Math.min(Math.max(options.duration, 1), 10) : 5;
                      numField.setValue(String(safeDuration));
                    }
                  }
                });
              }
            });
          }
        });

        if (blockInjectionCounter > 0) {
          workspace.fireChangeListener(new globalWin.Blockly.Events.BlockChange(
            null, 'edit', '', {}, {}
          ));
          console.log(`[AI Scanner] Successfully updated ${blockInjectionCounter} fields on workspace blocks.`);
        } else {
          console.warn('[AI Scanner] No matching block fields found to update.');
        }
      } catch (err) {
        console.error('[AI Scanner] Error injecting block parameters:', err);
      }
    }, 400);
  }
}

export const ScannerBridge = new ScannerBridgeClass();
export const scannerBridge = ScannerBridge;
